#!/usr/bin/env python3
"""Convert a monospace BDF font to a UTFT-format C header (D9 tooling).

UTFT layout (what gfx::Font reads): data[0]=width, data[1]=height,
data[2]=first char, data[3]=char count, then (w*h/8) bytes per glyph as a
continuous row-major MSB-first bitstream.

Usage:
  bdf_to_utft.py FONT.bdf ARRAY_NAME [--first 32] [--last 126] > header.h
"""

import argparse
import sys


def parse_bdf(path):
    """Return (cell_w, cell_h, ascent, {codepoint: glyph}) where glyph is
    (bbx_w, bbx_h, bbx_xoff, bbx_yoff, [row_bitmasks])."""
    cell_w = cell_h = ascent = None
    glyphs = {}
    with open(path, "r", encoding="utf-8") as f:
        lines = iter(f)
        encoding = None
        bbx = None
        for line in lines:
            tok = line.split()
            if not tok:
                continue
            if tok[0] == "FONTBOUNDINGBOX":
                cell_w, cell_h = int(tok[1]), int(tok[2])
            elif tok[0] == "FONT_ASCENT":
                ascent = int(tok[1])
            elif tok[0] == "ENCODING":
                encoding = int(tok[1])
            elif tok[0] == "BBX":
                bbx = (int(tok[1]), int(tok[2]), int(tok[3]), int(tok[4]))
            elif tok[0] == "BITMAP":
                rows = []
                for row in lines:
                    row = row.strip()
                    if row == "ENDCHAR":
                        break
                    rows.append(int(row, 16) if row else 0)
                if encoding is not None and encoding >= 0 and bbx is not None:
                    glyphs[encoding] = (*bbx, rows)
                encoding = None
                bbx = None
    if cell_w is None or cell_h is None or ascent is None:
        sys.exit("error: BDF missing FONTBOUNDINGBOX/FONT_ASCENT")
    return cell_w, cell_h, ascent, glyphs


def render_cell(cell_w, cell_h, ascent, glyph):
    """Rasterize one glyph into a cell_w x cell_h boolean grid."""
    bw, bh, xoff, yoff, rows = glyph
    grid = [[False] * cell_w for _ in range(cell_h)]
    top = ascent - (bh + yoff)  # y of the glyph's first bitmap row in the cell
    hex_bits = ((bw + 7) // 8) * 8  # BDF rows are padded to whole bytes
    for ry, mask in enumerate(rows):
        y = top + ry
        if not 0 <= y < cell_h:
            continue
        for rx in range(bw):
            if (mask >> (hex_bits - 1 - rx)) & 1:
                x = xoff + rx
                if 0 <= x < cell_w:
                    grid[y][x] = True
    return grid


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("bdf")
    ap.add_argument("array_name")
    ap.add_argument("--first", type=int, default=32)
    ap.add_argument("--last", type=int, default=126)
    args = ap.parse_args()

    cell_w, cell_h, ascent, glyphs = parse_bdf(args.bdf)
    if (cell_w * cell_h) % 8 != 0:
        sys.exit(f"error: cell {cell_w}x{cell_h} is not byte-divisible")
    count = args.last - args.first + 1

    out = [cell_w, cell_h, args.first, count]
    for cp in range(args.first, args.last + 1):
        grid = (render_cell(cell_w, cell_h, ascent, glyphs[cp])
                if cp in glyphs else [[False] * cell_w for _ in range(cell_h)])
        bits = [px for row in grid for px in row]
        for i in range(0, len(bits), 8):
            byte = 0
            for b in bits[i:i + 8]:
                byte = (byte << 1) | int(b)
            out.append(byte)

    per_glyph = (cell_w * cell_h) // 8
    print(f"// Generated by scripts/bdf_to_utft.py from {args.bdf.split('/')[-1]}")
    print(f"// {cell_w}x{cell_h}, chars {args.first}..{args.last}, "
          f"{len(out)} bytes. Do not edit by hand.")
    print(f"\nconst unsigned char {args.array_name}[] = {{")
    print(f"    0x{out[0]:02X}, 0x{out[1]:02X}, 0x{out[2]:02X}, 0x{out[3]:02X},")
    for g in range(count):
        base = 4 + g * per_glyph
        row = ", ".join(f"0x{b:02X}" for b in out[base:base + per_glyph])
        ch = chr(args.first + g)
        label = ch if ch not in "\\" else "backslash"
        print(f"    {row},  // {args.first + g} '{label}'")
    print("};")


if __name__ == "__main__":
    main()
