#!/usr/bin/env python3
"""Harvest the existing host suites into a differential-test corpus.

Phase 5.2 task 5.2.9. phase5.2-spec.md §6.1 makes the promise this implements:
"Rather than rewriting the existing suites, run every expression they already
contain through *both* evaluators and assert identical results. That turns 1,200
hand-written checks into a conformance harness for free."

The harvest works because a differential test needs no expected value — only
that the two pipelines agree. So a bare expression string is the whole input,
and the suites are full of them, including the error cases and stores that a
hand-written corpus would under-represent.

Every `check_*("...")` call contributes its first string literal. Calls whose
first argument is not a string literal (check(bool, ...), check_eq(long, ...))
are skipped by construction.

Usage:
    python3 scripts/gen-differential-corpus.py

Writes tests/host/differential_corpus.inc, which is checked in: the host suites
build from a shell script rather than CMake, so generating at build time would
buy nothing and cost a dependency. Re-run it when a suite gains expressions.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# The three evaluators being retired, plus the real engine they all escape to.
# test_unified is deliberately NOT a source: it pins the new evaluator, so
# harvesting it would compare the new evaluator against expectations written
# for the new evaluator.
SOURCES = [
    "tests/host/test_math.cpp",
    "tests/host/test_complex_expr.cpp",
    "tests/host/test_lists.cpp",
    "tests/host/test_matrix.cpp",
]

CALL = re.compile(r'\bcheck_[A-Za-z0-9_]*\(\s*"((?:[^"\\]|\\.)*)"')

HEADER = """// GENERATED by scripts/gen-differential-corpus.py — do not edit by hand.
//
// The differential corpus (5.2.9): every expression the existing host suites
// already contain, harvested so the old and new evaluators can be run against
// the same inputs. A differential check needs no expected value, only agreement,
// which is why a bare expression is the whole input.
//
// Re-run the generator when a suite gains expressions.
"""


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    out_path = root / "tests/host/differential_corpus.inc"

    blocks: list[tuple[str, list[str]]] = []
    seen: set[str] = set()
    total = 0
    for rel in SOURCES:
        path = root / rel
        if not path.exists():
            print(f"missing source: {rel}", file=sys.stderr)
            return 1
        found = []
        for expr in CALL.findall(path.read_text()):
            if not expr.strip() or expr in seen:
                continue  # empty-input cases are the driver's own concern
            seen.add(expr)
            found.append(expr)
        blocks.append((Path(rel).name, found))
        total += len(found)

    lines = [HEADER, "", "const char* const kCorpus[] = {"]
    for name, exprs in blocks:
        lines.append(f"    // {name} ({len(exprs)})")
        for expr in exprs:
            lines.append(f'    "{expr}",')
    lines.append("};")
    lines.append("")
    out_path.write_text("\n".join(lines))
    print(f"wrote {out_path.relative_to(root)}: {total} expressions from {len(SOURCES)} suites")
    return 0


if __name__ == "__main__":
    sys.exit(main())
