#!/usr/bin/env python3
"""Rasterize a (monospace) TTF into a UTFT-format C header at a fixed
bitmap cell size — the JuliaMono test-drive counterpart to bdf_to_utft.py
(testdrive 2026-07-20). Same on-device layout that gfx::Font reads:
data[0]=width, data[1]=height, data[2]=first, data[3]=count, then
(w*h/8) row-major MSB-first bytes per glyph.

  ttf_to_utft.py FONT.ttf ARRAY_NAME [--first 32] [--last 134] \
      [--width 8] [--height 16] [--pxsize 13] [--baseline 12] \
      [--map SLOT:CODEPOINT ...] [--threshold 128]

--map places a glyph from an arbitrary codepoint into a slot (e.g. the
angle sign or Greek letters into the high slots the ASCII range leaves
free). Glyphs are rendered anti-aliased then thresholded to 1bpp and
centered horizontally in the cell; --baseline is the cell row (0=top)
that the font baseline sits on.
"""

import argparse
import sys

import freetype


def render_cell(face, cp, w, h, baseline, threshold):
    """Rasterize one codepoint into a w x h boolean grid (or blank)."""
    grid = [[False] * w for _ in range(h)]
    if cp is None or face.get_char_index(cp) == 0:
        return grid
    face.load_char(cp, freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_NORMAL)
    bm = face.glyph.bitmap
    bw, bh = bm.width, bm.rows
    pitch = bm.pitch
    # Horizontal: center the ink in the cell. Vertical: baseline row minus
    # the glyph's bitmap_top (rows of ink above the baseline).
    x0 = (w - bw) // 2
    y0 = baseline - face.glyph.bitmap_top
    for ry in range(bh):
        for rx in range(bw):
            if bm.buffer[ry * pitch + rx] >= threshold:
                x, y = x0 + rx, y0 + ry
                if 0 <= x < w and 0 <= y < h:
                    grid[y][x] = True
    return grid


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("ttf")
    ap.add_argument("array_name")
    ap.add_argument("--first", type=int, default=32)
    ap.add_argument("--last", type=int, default=134)
    ap.add_argument("--width", type=int, default=8)
    ap.add_argument("--height", type=int, default=16)
    ap.add_argument("--pxsize", type=int, default=13)
    ap.add_argument("--baseline", type=int, default=12)
    ap.add_argument("--threshold", type=int, default=128)
    ap.add_argument("--map", action="append", default=[], metavar="SLOT:CODEPOINT")
    args = ap.parse_args()

    if (args.width * args.height) % 8 != 0:
        sys.exit(f"error: cell {args.width}x{args.height} is not byte-divisible")

    remap = {}
    for spec in args.map:
        slot, cp = (int(x, 0) for x in spec.split(":"))
        if not args.first <= slot <= args.last:
            sys.exit(f"error: --map slot {slot} outside {args.first}..{args.last}")
        remap[slot] = cp

    face = freetype.Face(args.ttf)
    face.set_pixel_sizes(0, args.pxsize)

    count = args.last - args.first + 1
    out = [args.width, args.height, args.first, count]
    for slot in range(args.first, args.last + 1):
        cp = remap.get(slot, slot)
        grid = render_cell(face, cp, args.width, args.height, args.baseline, args.threshold)
        bits = [px for row in grid for px in row]
        for i in range(0, len(bits), 8):
            byte = 0
            for b in bits[i:i + 8]:
                byte = (byte << 1) | int(b)
            out.append(byte)

    per_glyph = (args.width * args.height) // 8
    fam = face.family_name.decode() if face.family_name else args.ttf
    print(f"// Generated by scripts/ttf_to_utft.py from {fam} "
          f"({args.pxsize}px, baseline {args.baseline}).")
    print(f"// {args.width}x{args.height}, chars {args.first}..{args.last}, "
          f"{len(out)} bytes. Do not edit by hand.")
    print(f"\nconst unsigned char {args.array_name}[] = {{")
    print(f"    0x{out[0]:02X}, 0x{out[1]:02X}, 0x{out[2]:02X}, 0x{out[3]:02X},")
    for g in range(count):
        base = 4 + g * per_glyph
        row = ", ".join(f"0x{b:02X}" for b in out[base:base + per_glyph])
        slot = args.first + g
        if slot in remap:
            label = f"U+{remap[slot]:04X}"
        elif chr(slot) == "\\":
            label = "backslash"
        elif chr(slot).isprintable():
            label = chr(slot)
        else:
            label = f"0x{slot:02X}"
        print(f"    {row},  // {slot} '{label}'")
    print("};")


if __name__ == "__main__":
    main()
